"""initials_create

Revision ID: 43fde871bcac
Revises: 95025d690694
Create Date: 2024-05-18 16:06:55.858962+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "43fde871bcac"
down_revision: str | None = "95025d690694"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "initials",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("cid", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("fir", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("initials", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cid", "fir"),
        sa.UniqueConstraint("initials", "fir"),
    )
    op.create_index(op.f("ix_initials_id"), "initials", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_initials_id"), table_name="initials")
    op.drop_table("initial")
    # ### end Alembic commands ###
